export const LOADING = 'LOADING'

// AUTH
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT_SUCCESS ='LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'

// USERS
export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'

// NOTES
export const FETCH_NOTES = 'FETCH_NOTES'
export const FETCH_NOTES_ERROR = 'FETCH_NOTES_ERROR'

export const CREATE_NOTES = 'CREATE_NOTES'
export const CREATE_NOTES_ERROR = 'CREATE_NOTES_ERROR'

export const FETCH_NOTE = 'FETCH_NOTE'
export const FETCH_NOTE_ERROR = 'FETCH_NOTE_ERROR'

export const EDIT_NOTE = 'EDIT_NOTE'
export const EDIT_NOTE_ERROR = 'EDIT_NOTE_ERROR'

export const DELETE_NOTE = 'DELETE_NOTE'
export const DELETE_NOTE_ERROR = 'DELETE_NOTE_ERROR'